sudo: false

addons:
    apt:
      packages:
        - cmake
        - vtk
#      sources:
#        - kalakris-cmake

script:
#  - wget http://www.vtk.org/files/release/7.1/VTK-7.1.0.tar.gz
#  - tar -xf VTK-7.1.0.tar.gz
#  - mkdir VTKBin && cd VTKBin && cmake ../VTK-7.1.0 -DBUILD_SHARED_LIBS==OFF -DCMAKE_BUILD_TYPE=Release && make -j 2 && cd ..
#  - cmake . -DVTK_DIR=/home/travis/build/valette/VTKBin -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS==OFF && make -j 2
#  - sudo apt-get install -y vtk
  - cmake . -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS==OFF && make -j 2

language: cpp
cache: ccache
